source 'https://github.com/CocoaPods/Specs.git'
platform :ios,			'8.0'
inhibit_all_warnings!

target:MengMailCore

xcodeproj 'MengMailCore.xcodeproj'
workspace 'MengMailCore.xcworkspace'

pod 'Masonry', '~> 0.6.3'
pod 'mailcore2-ios', '~> 0.6.4'

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end

